[package]
name = "mkpub"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-config = { version = "0.56.1", default-features = false, features = ["client-hyper", "rustls", "rt-tokio"] }
aws-sdk-s3 = "0.30.0"
clap = { version = "4.4.2", features = ["derive", "env"] }
directories = "5.0.1"
dirs = "5.0.1"
miette = { version = "5.10.0", features = ["fancy"] }
mime_guess = "2.0.4"
serde = { version = "1.0.188", features = ["derive"] }
thiserror = "1.0.44"
tokio = { version = "1.32.0", features = ["rt", "macros"] }
toml = "0.7.6"
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
url = { version = "2.4.0", features = ["serde"] }

[profile.release]
lto = "fat"
codegen-units = 1
strip = "debuginfo"
panic = "abort"
