name: Check and Build

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:

permissions:
  actions: read
  contents: read
  checks: write

jobs:
  # We have individual jobs for the stable and nightly toolchains as this lets
  # us run the pipelines in parallel so one can proceed even if the other fails.
  check-and-test:
    name: Clippy and Tests
    strategy:
      matrix:
        rust: [stable, nightly]
      fail-fast: false
    uses: ./.github/workflows/clippy_and_tests.yaml
    with:
      toolchain: ${{ matrix.rust }}
    secrets:
      codecov-token: ${{ secrets.CODECOV_TOKEN }}
