on:
  workflow_dispatch:
  push:
    tags:
    - v*

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4
    - name: Install Rust
      run: |
        rustup install stable --profile default
        rustup default stable
    - name: Run build
      run: |
        cargo build --release
    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: mkpub-x86_64-unknown-linux-gnu
        path: target/release/mkpub
